name: JAVA CI
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2  
      - run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh 
      - name: Upload
        uses: actions/upload-artifacts@v2
        with:
          name: code
          path: .